[package]
name = "relayer-probe"
version = { workspace = true }
edition = { workspace = true }
publish = false

[[bin]]
name = "relayer-probe"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
jito-protos = { workspace = true }
solana-keypair = { workspace = true }
solana-signer = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
